using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Niemand.Helpers.Notifications;
public class PushNotifier(IHaContext ha, IServices services)
{

    public enum Recipient
    {
        All,
        Eugene,
        Hailey
    }

    private readonly Dictionary<Recipient, string> RecipientMap = new()
    {
        { Recipient.Eugene, "mobile_app_eugenes_iphone" },
        { Recipient.Hailey, "mobile_app_haileys_iphone" }
    };

    public void Notify(Recipient recipient, string title, string message, double volume = 0.2, bool critical = false, string soundName = "default")
    {
        var notify_data = new
        {
            message,
            title,
            data = new
            {
                push = new
                {
                    sound = new
                    {
                        name = soundName,
                        critical = critical ? 1 : 0,
                        volume
                    }
                }
            }
        };

        if (recipient != Recipient.All)
        {
            ha.CallService("notify", RecipientMap[recipient], null, notify_data);
            return;
        }

        foreach (var recipientValue in RecipientMap.Values)
            ha.CallService("notify", recipientValue, null, notify_data);

    }

    /*
     3rdParty_DirectionDown_Haptic.caf
 3rdParty_DirectionUp_Haptic.caf
 3rdParty_Failure_Haptic.caf
 3rdParty_Retry_Haptic.caf
 3rdParty_Start_Haptic.caf
 3rdParty_Stop_Haptic.caf
 3rdParty_Success_Haptic.caf
 access_scan_complete.caf
 AccessSanComplete_Haptic
 acknowledgment_received.caf
 acknowledgment_sent.caf
 alarm.caf
 Alarm_Haptic.caf
 Alarm_Nightstand_Haptic.caf
 Alert_3rdParty_Haptic.caf
 Alert_3rdParty_Salient_Haptic.caf
 Alert_ActivityFriendsGoalAttained_Haptic.caf
 Alert_ActivityGoalAttained_Haptic.caf
 Alert_ActivityGoalAttained_Salient_Haptic.caf
 Alert_ActivityGoalBehind_Haptic.caf
 Alert_ActivityGoalBehind_Salient_Haptic.caf
 Alert_ActivityGoalClose_Haptic.caf
 Alert_BatteryLow_10p_Haptic.caf
 Alert_BatteryLow_5p_Haptic.caf
 Alert_BatteryLow_5p_Salient_Haptic.caf
 Alert_Calendar_Haptic.caf
 Alert_Calendar_Salient_Haptic.caf
 Alert_Health_Haptic.caf
 Alert_Mail_Haptic.caf
 Alert_Mail_Salient_Haptic.caf
 Alert_MapsDirectionsInApp_Haptic.caf
 Alert_Messages_1_Haptic.caf
 Alert_Messages_1_Salient_Haptic.caf
 Alert_Messages_2_Haptic.caf
 Alert_Messages_3_Haptic.caf
 Alert_PassbookBalance_Haptic.caf
 Alert_PassbookGeofence_Haptic.caf
 Alert_PassbookGeofence_Salient_Haptic.caf
 Alert_PhotostreamActivity_Haptic.caf
 Alert_ReminderDue_Haptic.caf
 Alert_ReminderDue_Salient_Haptic.caf
 Alert_SpartanConnected_LowLatency_Haptic.caf
 Alert_SpartanConnecting_Haptic.caf
 Alert_SpartanConnecting_LowLatency_Haptic.caf
 Alert_SpartanDisconnected_LowLatency_Haptic.caf
 Alert_Voicemail_Haptic.caf
 Alert_Voicemail_Salient_Haptic.caf
 Alert_WalkieTalkie_Haptic.caf
 Anticipate.caf
 AutoUnlock_Haptic.caf
 BatteryMagsafe_Haptic.caf
 Beat_Haptic.caf
 begin_record.caf
 Bloom.caf
 BuddyMigrationStart_Haptic.caf
 BuddyPairingFailure_Haptic.caf
 BuddyPairingRemoteConnection_Haptic.caf
 BuddyPairingRemoteTap_Haptic.caf
 BuddyPairingSuccess_Haptic.caf
 busy_tone_ansi.caf
 busy_tone_cept.caf
 call_waiting_tone_ansi.caf
 call_waiting_tone_cept.caf
 Calypso.caf
 camera_shutter_burst.caf
 camera_shutter_burst_begin.caf
 camera_shutter_burst_end.caf
 camera_timer_countdown.caf
 camera_timer_final_second.caf
 CameraCountdownImminent_Haptic.caf
 CameraCountdownTick_Haptic.caf
 CameraShutter_Haptic.caf
 Choo_Choo.caf
 connect_power.caf
 ct-busy.caf
 ct-call-waiting.caf
 ct-congestion.caf
 ct-error.caf
 ct-keytone2.caf
 ct-path-ack.caf
 Descent.caf
 Detent_Haptic.caf
 DoNotDisturb_Haptic.caf
 dtmf-0.caf
 dtmf-1.caf
 dtmf-2.caf
 dtmf-3.caf
 dtmf-4.caf
 dtmf-5.caf
 dtmf-6.caf
 dtmf-7.caf
 dtmf-8.caf
 dtmf-9.caf
 dtmf-pound.caf
 dtmf-star.caf
 end_call_tone_cept.caf
 end_record.caf
 engage_power.caf
 engage_power_short.caf
 ET_BeginNotification_Haptic.caf
 ET_BeginNotification_Salient_Haptic.caf
 ET_RemoteTap_Receive_Haptic.caf
 ET_RemoteTap_Send_Haptic.caf
 Fanfare.caf
 focus_change_app_icon.caf
 focus_change_keyboard.caf
 focus_change_large.caf
 focus_change_small.caf
 go_to_sleep_alert.caf
 GoToSleep_Haptic.caf
 HealthNotificaiton.caf
 HourlyChime_Haptic.caf
 HummingbirdCompletion_Haptic.caf
 HummingbirdNotification_Haptic.caf
 jbl_ambiguous.caf
 jbl_begin.caf
 jbl_cancel.caf
 jbl_confirm.caf
 jbl_no_match.caf
 key_press_click.caf
 key_press_delete.caf
 key_press_modifier.caf
 keyboard_press_clear.caf
 keyboard_press_delete.caf
 keyboard_press_normal.caf
 Ladder.caf
 lock.caf
 long_low_short_high.caf
 low_power.caf
 mail-sent.caf
 MessagesIncoming_Haptic.caf
 MessagesOutgoing_Haptic.caf
 middle_9_short_double_low.caf
 Minuet.caf
 multiway_invitation.caf
 MultiwayInvitation.caf
 MultiwayJoin.caf
 MultiwayLeave.caf
 navigation_pop.caf
 navigation_push.caf
 NavigationGenericManeuver_Haptic.caf
 NavigationGenericManeuver_Salient_Haptic.caf
 NavigationLeftTurn_Haptic.caf
 NavigationLeftTurn_Salient_Haptic.caf
 NavigationRightTurn_Haptic.caf
 NavigationRightTurn_Salient_Haptic.caf
 new-mail.caf
 News_Flash.caf
 nfc_scan_complete.caf
 Noir.caf
 Notification_Haptic.caf
 Notification_Salient_Haptic.caf
 OnOffPasscodeFailure_Haptic.caf
 OnOffPasscodeUnlock_Haptic.caf
 OnOffPasscodeUnlockCampanion_Haptic.caf
 OrbExit_Haptic.caf
 OrbLayers_Haptic.caf
 payment_failure.caf
 payment_success.caf
 PhoneAnswer_Haptic.caf
 PhoneHangUp_Haptic.caf
 PhoneHold_Haptic.caf
 photoShutter.caf
 PhotosZoomDetent_Haptic.caf
 Preview_AudioAndHaptic.caf
 QB_Dictation_Haptic.caf
 QB_Dictation_Off_Haptic.caf
 ReceivedMessage.caf
 RemoteCameraShutterBurstBegin_Haptic.caf
 RemoteCameraShutterBurstEnd_Haptic.caf
 ringback_tone_ansi.caf
 ringback_tone_aus.caf
 ringback_tone_cept.caf
 ringback_tone_hk.caf
 ringback_tone_uk.caf
 RingerChanged.caf
 Ringtone_2_Ducked_Haptic-sashimi.caf
 Ringtone_2_Haptic-sashimi.caf
 Ringtone_UK_Haptic.caf
 Ringtone_US_Haptic.caf
 RingtoneDucked_UK_Haptic.caf
 RingtoneDucked_US_Haptic.caf
 SalientNotification_Haptic.caf
 SedentaryTimer_Haptic.caf
 SedentaryTimer_Salient_Haptic.caf
 SentMessage.caf
 shake.caf
 Sherwood_Forest.caf
 short_double_high.caf
 short_double_low.caf
 short_low_high.caf
 SIMToolkitCallDropped.caf
 SIMToolkitGeneralBeep.caf
 SIMToolkitNegativeACK.caf
 SIMToolkitPositiveACK.caf
 SIMToolkitSMS.caf
 SiriAutoSend_Haptic.caf
 SiriStart_Haptic.caf
 SiriStopFailure_Haptic.caf
 SiriStopSuccess_Haptic.caf
 sms-received1.caf
 sms-received1.caf
 sms-received2.caf
 sms-received3.caf
 sms-received4.caf
 sms-received5.caf
 sms-received6.caf
 SOSEmergencyContactTextPrompt_Haptic.caf
 SOSFallDetection_Haptic-Newton.caf
 Spell.caf
 Stockholm_Haptic.caf
 StockholmActive_Haptic.caf
 StockholmActiveSingleCycle_Haptic.caf
 StockholmFailure_Haptic.caf
 StopwatchLap_Haptic.caf
 StopwatchReset_Haptic.caf
 StopwatchStart_Haptic.caf
 StopwatchStop_Haptic.caf
 Suspense.caf
 Swish.caf
 SwTest1_Haptic.caf
 SystemStartup_Haptic.caf
 Telegraph.caf
 Timer_Haptic.caf
 TimerCancel_Haptic.caf
 TimerPause_Haptic.caf
 TimerStart_Haptic.caf
 TimerWheelHoursDetent_Haptic.caf
 TimerWheelMinutesDetent_Haptic.caf
 Tink.caf
 Tiptoes.caf
 Tock.caf
 tweet_sent.caf
 Typewriters.caf
 UISwipe_Haptic.caf
 UISwitch_Off_Haptic.caf
 UISwitch_On_Haptic.caf
 Update.caf
 ussd.caf
 vc~ended.caf
 vc~invitation-accepted.caf
 vc~ringing.caf
 vc~ringing_watch.caf
 VoiceOver_Click_Haptic.caf
 WalkieTalkieActiveEnd_Haptic.caf
 WalkieTalkieActiveStart_Haptic.caf
 WalkieTalkieReceiveEnd_Haptic.caf
 WalkieTalkieReceiveStart_Haptic.caf
 warsaw.caf
 Warsaw_Haptic.caf
 wheels_of_time.caf
 WorkoutComplete_Haptic.caf
 WorkoutCompleteAutoDetect.caf
 WorkoutCountdown_Haptic.caf
 WorkoutPaceAbove.caf
 WorkoutPaceBelow.caf
 WorkoutPaused_Haptic.caf
 WorkoutPressStart_Haptic.caf
 WorkoutResumed_Haptic.caf
 WorkoutResumedAutoDetect.caf
 WorkoutSaved_Haptic.caf
 WorkoutSelect_Haptic.caf
 WorkoutStartAutoDetect.caf
     */
}
