lightsManager:
  class: LightsManager.StartUp
  nd_user_id: ef606e2918da4355ba036a019cdcc6a0
  guard_timeout: 300
  min_duration: 5
  max_duration: 30
  rooms:
  - name: Study
    timeout: 300
    presence_entity_ids:
      - binary_sensor.office_motion
      - binary_sensor.study
    keep_alive_entity_ids:
      - binary_sensor.eugene_laptop_in_use
      - binary_sensor.haileys_macbook_air_active
    control_entity_ids:
      - light.office
      - switch.office_skylight
    night_time_entity_id: input_select.house_mode
    night_time_entity_states:
      - night
      - sleeping
    night_control_entity_ids:
      - light.office
    lux_limit_entity_id: input_number.office_lux_limit
    lux_entity_id: sensor.office_lux
    circadian_switch_entity_id: switch.adaptive_lighting_study
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_night
    - armed_away
    debug: true

  - name: Dining
    presence_entity_ids:
      - binary_sensor.dining_motion
      - binary_sensor.dining
    control_entity_ids:
      - light.dining
      - light.dining_wall
    timeout: 300
    nightTimeout: 90
    lux_entity_id: sensor.dining_lux
    lux_limit_entity_id: input_number.dining_lux_limit
    night_time_entity_id: input_select.house_mode
    night_time_entity_states:
      - night
      - sleeping
    night_control_entity_ids:
      - light.dining_1
    circadian_switch_entity_id: switch.circadian_lighting_circadian_dining
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_night
    - armed_away
    debug: true

  - name: Fish
    presence_entity_ids:
      - binary_sensor.dining_motion
      - binary_sensor.dining
    control_entity_ids:
      - switch.plug_2
    timeout: 900
    night_time_entity_id: input_select.house_mode
    night_time_entity_states:
      - night
      - sleeping
    night_control_entity_ids:
      - light.dining_1
    debug: true

  - name: Landing
    presence_entity_ids:
      - binary_sensor.landing_motion
      - binary_sensor.landing
    control_entity_ids:
      - light.landing_day
      - light.landing_night
    night_time_entity_id: input_select.house_mode
    night_time_entity_states:
      - night
      - sleeping
    night_control_entity_ids:
      - light.landing_night
    timeout: 90
    lux_entity_id: sensor.landing_lux
    lux_limit_entity_id: input_number.landing_lux_limit
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_away
    debug: true

  - name: Porch
    presence_entity_ids:
      - binary_sensor.front_door
      - binary_sensor.niemand_front_door_motion
    keep_alive_entity_ids:
      - binary_sensor.front_door
    control_entity_ids:
      - light.porch
    timeout: 90
    condition_entity_id: sun.sun
    condition_entity_state: below_horizon
    debug: true

  - name: Aaron
    timeout: 300
    nightTimeout: 90
    presence_entity_ids:
      - binary_sensor.aaron_motion
    control_entity_ids:
      - light.aaron
    lux_entity_id: sensor.aaron_lux
    lux_limit_entity_id: input_number.aaron_lux_limit
    night_time_entity_id: input_select.house_mode
    night_time_entity_states:
      - night
      - sleeping
    night_control_entity_ids:
      - light.aaron_2
    circadian_switch_entity_id: switch.circadian_lighting_circadian_aaron
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_away

  - name: Jayden
    timeout: 300
    nightTimeout: 600
    presence_entity_ids:
      - binary_sensor.jayden_motion
    control_entity_ids:
      - light.jayden
    lux_entity_id: sensor.jayden_lux
    lux_limit_entity_id: input_number.jayden_lux_limit
    night_time_entity_id: input_select.house_mode
    night_time_entity_states:
      - night
      - sleeping
    night_control_entity_ids:
      - switch.tuya_socket_3
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_away

  - name: Hallway
    timeout: 300
    presence_entity_ids:
      - binary_sensor.landing_motion
      - binary_sensor.hallway
    control_entity_ids:
      - light.hallway
    lux_limit_entity_id: input_number.hallway_lux_limit
    lux_entity_id: sensor.entrance_lux
    circadian_switch_entity_id: switch.adaptive_lighting_hallway
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_night
    - armed_away
    debug: true

  - name: Entrance
    timeout: 300
    presence_entity_ids:
      - binary_sensor.entrance_motion
    control_entity_ids:
      - light.entrance
    lux_limit_entity_id: input_number.entrance_lux_limit
    lux_entity_id: sensor.entrance_lux
    circadian_switch_entity_id: switch.adaptive_lighting_entrance
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_night
    - armed_away
    debug: true

  - name: Master
    timeout: 300
    nightTimeout: 90
    presence_entity_ids:
      - binary_sensor.master_motion
    control_entity_ids:
      - light.master
    lux_entity_id: sensor.master_lux
    lux_limit_entity_id: input_number.master_lux_limit
    night_time_entity_id: input_select.house_mode
    night_time_entity_states:
      - night
      - sleeping
    night_control_entity_ids:
      - light.master_2
    circadian_switch_entity_id: switch.circadian_lighting_circadian_master
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_away

  - name: Lounge
    timeout: 300
    nightTimeout: 300
    presence_entity_ids:
      - binary_sensor.lounge_motion
      - binary_sensor.lounge
    control_entity_ids:
      - light.lounge
    lux_entity_id: sensor.lounge_lux
    lux_limit_entity_id: input_number.lounge_lux_limit
    keep_alive_entity_ids:
      - switch.lg_tv
    night_time_entity_id: input_select.house_mode
    night_time_entity_states:
      - night
      - sleeping
    night_control_entity_ids:
      - light.floor
    circadian_switch_entity_id: switch.adaptive_lighting_floor
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_night
    - armed_away
    debug: true

  - name: Playroom
    timeout: 300
    presence_entity_ids:
      - binary_sensor.playroom_motion
    control_entity_ids:
      - light.playroom
    lux_entity_id: sensor.playroom_lux
    lux_limit_entity_id: input_number.playroom_lux_limit
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_away

  - name: Kitchen
    timeout: 300
    presence_entity_ids:
      - binary_sensor.kitchen_motion
      - binary_sensor.kitchen
    control_entity_ids:
      - light.kitchen
    lux_entity_id: sensor.kitchen_lux
    lux_limit_entity_id: input_number.kitchen_lux_limit
    circadian_switch_entity_id: switch.adaptive_lighting_kitchen
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_night
    - armed_away
    debug: true

  - name: Toilet
    timeout: 300
    presence_entity_ids:
      - binary_sensor.toilet_motion
    control_entity_ids:
      - light.toilet
    lux_entity_id: sensor.toilet_lux
    lux_limit_entity_id: input_number.toilet_lux_limit
    circadian_switch_entity_id: switch.adaptive_lighting_toilet
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_night
    - armed_away
    debug: true

  - name: Utility
    timeout: 300
    presence_entity_ids:
      - binary_sensor.utility_motion
    control_entity_ids:
      - light.utility
    lux_entity_id: sensor.utility_lux
    lux_limit_entity_id: input_number.utility_lux_limit
    circadian_switch_entity_id: switch.adaptive_lighting_utility
    night_time_entity_id: input_select.house_mode
    night_time_entity_states:
      - night
      - sleeping
    night_control_entity_ids:
      - light.utility_1
    random_entity_id: alarm_control_panel.alarmo
    random_states:
    - armed_night
    - armed_away
    debug: true