Niemand.Helpers.AlexaConfig:
  Devices:
    media_player.office:
        DayVolume: 0.4
        NightVolume: 0.3
        NightWhisper: false
    media_player.kitchen:
        DayVolume: 0.5
        NightVolume: 0.2
        NightWhisper: false